import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/_site/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | Maxalena L." },
      { name: "description", content: "Privacy practices for maxalena.com." },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-14">
      <h1 className="font-display text-5xl">Privacy Policy</h1>
      <p className="mt-4 text-sm text-taupe">Last updated 13 September 2026</p>
      <div className="gold-rule my-8" />
      <div className="space-y-5 leading-8 text-parchment">
        <p>This website is the official author site of Maxalena L.</p>
        <p>
          If you use the contact form, we process the name, email address, subject, and message you submit so the
          enquiry can be read and, where appropriate, answered. Those details are not used for marketing lists.
        </p>
        <p>This site does not operate a newsletter or mailing list.</p>
        <p>Information that may be processed:</p>
        <ul className="list-disc pl-5">
          <li>Contact-form submissions (name, email, subject, message).</li>
          <li>Essential cookies required for the site and, where used, the private author login.</li>
          <li>Security and hosting logs generated by the hosting providers.</li>
          <li>Retailer-link destinations if you choose to follow a purchase or reading link.</li>
        </ul>
        <p>No public author email address is published on this site.</p>
      </div>
    </div>
  );
}
