import { fetchSettings } from "@/lib/content";
import { legalReady } from "@/lib/legal";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Maxalena L.",
  description: "Privacy practices for maxalena.com.",
};

export default async function PrivacyPage() {
  const settings = await fetchSettings().catch(() => ({}));
  const legal = legalReady(settings);
  return (
    <div className="mx-auto max-w-3xl px-5 py-14">
      <h1 className="font-display text-5xl">Privacy Policy</h1>
      <p className="mt-4 text-sm text-[var(--taupe)]">Last updated 13 September 2026</p>
      <div className="gold-rule my-8" />
      <div className="space-y-5 leading-8 text-[var(--parchment)]">
        <p>
          This website is the official author site of {legal.legalName}. It is hosted by {legal.hosting}.
        </p>
        <p>
          The public site does not operate a newsletter, mailing list, waitlist, or public contact form, and it does not collect names or email addresses from visitors for correspondence or marketing.
        </p>
        <p>Information that may be processed:</p>
        <ul className="list-disc pl-5">
          <li>Essential cookies required for the site and, where used, the private author login.</li>
          <li>Security and hosting logs generated by the hosting providers.</li>
          {legal.analytics && <li>Privacy-conscious analytics via {legal.analytics}.</li>}
          <li>Retailer-link destinations if you choose to follow a purchase or reading link.</li>
        </ul>
        {legal.jurisdiction && <p>Governing jurisdiction: {legal.jurisdiction}.</p>}
        {legal.contactMethod && <p>Formal legal correspondence: {legal.contactMethod}.</p>}
        {!legal.contactMethod && (
          <p>No public email address is published. A formal legal contact method will appear here if one is configured.</p>
        )}
      </div>
    </div>
  );
}
