/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteBooksRouteImport } from './routes/_site.books'
import { Route as SiteCharactersRouteImport } from './routes/_site.characters'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCookiesRouteImport } from './routes/_site.cookies'
import { Route as SiteCopyrightRouteImport } from './routes/_site.copyright'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as SiteBooksIndexRouteImport } from './routes/_site.books.index'
import { Route as SiteBooksSlugRouteImport } from './routes/_site.books.$slug'
import { Route as SiteBooksSlugIndexRouteImport } from './routes/_site.books.$slug.index'
import { Route as SiteBooksSlugPreviewRouteImport } from './routes/_site.books.$slug.preview'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBooksRoute = SiteBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCharactersRoute = SiteCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCookiesRoute = SiteCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCopyrightRoute = SiteCopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const SiteBooksIndexRoute = SiteBooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteBooksRoute,
} as any)
const SiteBooksSlugRoute = SiteBooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteBooksRoute,
} as any)
const SiteBooksSlugIndexRoute = SiteBooksSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteBooksSlugRoute,
} as any)
const SiteBooksSlugPreviewRoute = SiteBooksSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => SiteBooksSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/books': typeof SiteBooksRouteWithChildren
  '/characters': typeof SiteCharactersRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/copyright': typeof SiteCopyrightRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/books/$slug': typeof SiteBooksSlugRouteWithChildren
  '/books/': typeof SiteBooksIndexRoute
  '/books/$slug/preview': typeof SiteBooksSlugPreviewRoute
  '/books/$slug/': typeof SiteBooksSlugIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/characters': typeof SiteCharactersRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/copyright': typeof SiteCopyrightRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof SiteBooksIndexRoute
  '/books/$slug/preview': typeof SiteBooksSlugPreviewRoute
  '/books/$slug': typeof SiteBooksSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/books': typeof SiteBooksRouteWithChildren
  '/_site/characters': typeof SiteCharactersRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/cookies': typeof SiteCookiesRoute
  '/_site/copyright': typeof SiteCopyrightRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/books/$slug': typeof SiteBooksSlugRouteWithChildren
  '/_site/books/': typeof SiteBooksIndexRoute
  '/_site/books/$slug/preview': typeof SiteBooksSlugPreviewRoute
  '/_site/books/$slug/': typeof SiteBooksSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/books'
    | '/characters'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/admin/'
    | '/books/$slug'
    | '/books/'
    | '/books/$slug/preview'
    | '/books/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/characters'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/'
    | '/admin'
    | '/books'
    | '/books/$slug/preview'
    | '/books/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/about'
    | '/_site/books'
    | '/_site/characters'
    | '/_site/contact'
    | '/_site/cookies'
    | '/_site/copyright'
    | '/_site/privacy'
    | '/_site/terms'
    | '/admin/login'
    | '/_site/'
    | '/admin/'
    | '/_site/books/$slug'
    | '/_site/books/'
    | '/_site/books/$slug/preview'
    | '/_site/books/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/books': {
      id: '/_site/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof SiteBooksRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/characters': {
      id: '/_site/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof SiteCharactersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cookies': {
      id: '/_site/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof SiteCookiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/copyright': {
      id: '/_site/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof SiteCopyrightRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/books/': {
      id: '/_site/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof SiteBooksIndexRouteImport
      parentRoute: typeof SiteBooksRoute
    }
    '/_site/books/$slug': {
      id: '/_site/books/$slug'
      path: '/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof SiteBooksSlugRouteImport
      parentRoute: typeof SiteBooksRoute
    }
    '/_site/books/$slug/': {
      id: '/_site/books/$slug/'
      path: '/'
      fullPath: '/books/$slug/'
      preLoaderRoute: typeof SiteBooksSlugIndexRouteImport
      parentRoute: typeof SiteBooksSlugRoute
    }
    '/_site/books/$slug/preview': {
      id: '/_site/books/$slug/preview'
      path: '/preview'
      fullPath: '/books/$slug/preview'
      preLoaderRoute: typeof SiteBooksSlugPreviewRouteImport
      parentRoute: typeof SiteBooksSlugRoute
    }
  }
}

interface SiteBooksSlugRouteChildren {
  SiteBooksSlugPreviewRoute: typeof SiteBooksSlugPreviewRoute
  SiteBooksSlugIndexRoute: typeof SiteBooksSlugIndexRoute
}

const SiteBooksSlugRouteChildren: SiteBooksSlugRouteChildren = {
  SiteBooksSlugPreviewRoute: SiteBooksSlugPreviewRoute,
  SiteBooksSlugIndexRoute: SiteBooksSlugIndexRoute,
}

const SiteBooksSlugRouteWithChildren = SiteBooksSlugRoute._addFileChildren(
  SiteBooksSlugRouteChildren,
)

interface SiteBooksRouteChildren {
  SiteBooksSlugRoute: typeof SiteBooksSlugRouteWithChildren
  SiteBooksIndexRoute: typeof SiteBooksIndexRoute
}

const SiteBooksRouteChildren: SiteBooksRouteChildren = {
  SiteBooksSlugRoute: SiteBooksSlugRouteWithChildren,
  SiteBooksIndexRoute: SiteBooksIndexRoute,
}

const SiteBooksRouteWithChildren = SiteBooksRoute._addFileChildren(
  SiteBooksRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBooksRoute: typeof SiteBooksRouteWithChildren
  SiteCharactersRoute: typeof SiteCharactersRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCookiesRoute: typeof SiteCookiesRoute
  SiteCopyrightRoute: typeof SiteCopyrightRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBooksRoute: SiteBooksRouteWithChildren,
  SiteCharactersRoute: SiteCharactersRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCookiesRoute: SiteCookiesRoute,
  SiteCopyrightRoute: SiteCopyrightRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
